### ISSUE TITLE
PHP warnings on first installation

### ISSUE THREAD

**Issue by afercia** [swissspidy/preferred-languages#11] opened 2017-05-20 12:28 UTC
On first installation, when the `preferred_languages` option doesn't exist yet, getting lots of warnings:
```
Warning: explode() expects parameter 2 to be string, array given in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/preferred-languages/preferred-languages.php on line 115

Warning: array_filter() expects parameter 1 to be array, null given in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/preferred-languages/preferred-languages.php on line 115
```

![screen shot 2017-05-20 at 14 20 29](https://cloud.githubusercontent.com/assets/1682452/26275726/03836486-3d68-11e7-8c47-28113411e62a.jpg)

Of course, after the first save the warnings disappear.

Not sure if it matters. worth nothing the option get saved with a leading comma:

<img width="884" alt="screen shot 2017-05-20 at 14 21 29" src="https://cloud.githubusercontent.com/assets/1682452/26275755/7f86d252-3d68-11e7-830a-382de1638361.png">

**Comment by swissspidy** [comment] 2017-05-20 17:32
Thanks for your report.

I fixed the notices now, but I cannot reproduce the thing with the leading comma right now…

**Comment by afercia** [comment] 2017-05-21 09:29
Hm after the warnings are gone, and saved again, I don't see the leading comma any longer. Maybe an edge case where one or two empty locale values get saved?

**Comment by swissspidy** [comment] 2017-05-21 10:51
Hmm the only empty value could be for en_US, but I have an extra fix for that and it was saved properly in your screenshot.

Closing now until it pops up again…

**Closed by swissspidy** 2017-05-21 10:51 UTC
Labels: bug
