### ISSUE TITLE
Doesn't work with `load_script_textdomain`

### ISSUE THREAD

**Issue by strarsis** [swissspidy/preferred-languages#566] opened 2022-12-11 21:54 UTC
[`load_script_textdomain`](https://developer.wordpress.org/reference/functions/load_script_textdomain/) that is used to load translation for scripts (as for Dashboard widgets, Gutenberg). But apparently it is (or the function / hooks it uses) not hooked into by this plugin, as the language files in the fallback languages are not loaded - just the primary one.

Another aspect to consider is that for JavaScript WordPress uses `JSON` files - the translation strings from those JSON files must also be merged together for the preferred languages.

**Comment by swissspidy** [comment] 2022-12-12 07:29
Can you please try 2.0.0 Beta? https://github.com/swissspidy/preferred-languages/releases/tag/2.0.0-beta.1

It fixes some issues with script translations.

**Comment by strarsis** [comment] 2022-12-13 22:47
@swissspidy: Thanks! After some further debugging I noticed that the current stable version of the plugin also works - the underlying issue as something different:

The language file that wasn't used had the name `google-site-kit-de_DE-6aa9f591365243ecf946a2215cc88d51.json`.
But on a different (staging/test) environment, the language file was actually used - and its name there is `google-site-kit-de_DE-bae57ff7f6c5e0187fc9ebaab93a7b58.json`.
After having renamed the language file from `google-site-kit-de_DE-6aa9f591365243ecf946a2215cc88d51.json` to `google-site-kit-de_DE-bae57ff7f6c5e0187fc9ebaab93a7b58.json` the language file is now correctly used.

So why is an incorrect language file name used? Is this an issue with `wp i18n` (which is used to install and update the language files), or with the WordPress core, or with the plugin that should use the language files (Google Site Kit plugin)?

**Comment by swissspidy** [comment] 2022-12-13 23:36
Ah, you are using Site Kit!

In that case the issue is that the JS file name changed between plugin releases (they do thst for cache invalidation purposes), but translations were not updated accordingly, thus causing this mismatch. I know that Site Kit specifically has this issue and is aware of it, the team and I had several discussions about it (I also work at Google). So far we haven‘t found a good solution though.

Closing since this is a known issue with Site Kit and the WP translation system and not abug with this plugin.

**Closed by swissspidy** 2022-12-13 23:36 UTC
Labels: Unconfirmed

**Comment by strarsis** [comment] 2022-12-13 23:40
@swissspidy: Thanks for the explanation, now it makes sense!

**Comment by strarsis** [comment] 2022-12-13 23:56
@swissspidy: When the WordPress language updater or `wp i18n` CLI would not skip those JSON files, this wouldn't be as an issue as the new JSON files with new, matching hash are then downloaded.
