### ISSUE TITLE
Incompatibility with Polylang Pro plugin

### ISSUE THREAD

**Issue by markhowellsmead** [swissspidy/preferred-languages#353] opened 2021-03-08 09:33 UTC
When I use `date_i18n` or `get_the_date` when Polylang (Pro) and the Preferred Languages plugin are in use, and the user-preferred languages are set to _Deutsch (Schweiz)_ and fallback _Deutsch (Sie)_, the date is always returned in the default site language. e.g. `17. Februar 2021` instead of `17. février 2021` for a Post translated to French.

## Steps to reproduce the issue

1. Install the plugins detailed above and configure the site with German and French as Polylang languages.
2. Set the WordPress languages as _Deutsch (Schweiz)_ and fallback _Deutsch (Sie)_ using the Preferred Languages plugin.
3. Load a French Post and review the `date_i18n` output.

## Expected behavior and actual behavior

When I follow those steps, I see the date in German.
I was expecting the date in French.

See also https://github.com/polylang/polylang/issues/776.

**Comment by swissspidy** [comment] 2021-03-08 09:38
Odd that this happens, since the plugin _should_ be bailing early if a plugin like Polylang is already filtering the current locale:

https://github.com/swissspidy/preferred-languages/blob/a11940282f955acc3a58f64d806ef1588f6c093d/inc/functions.php#L352-L355

https://github.com/swissspidy/preferred-languages/blob/a11940282f955acc3a58f64d806ef1588f6c093d/inc/functions.php#L787-L790

I'll try to see whether I can reproduce this with the free version.

**Comment by swissspidy** [comment] 2021-03-09 16:06
I am not able to reproduce this, with the free version at least.

**Preferred Languages**

<img width="698" alt="Screenshot 2021-03-09 at 17 04 20" src="https://user-images.githubusercontent.com/841956/110500457-7f8b9c00-80f9-11eb-8c00-e64c9c58bfc7.png">

**Polylang Languages:**

<img width="978" alt="Screenshot 2021-03-09 at 17 02 41" src="https://user-images.githubusercontent.com/841956/110500228-43f0d200-80f9-11eb-878c-a2c9ffacf55e.png">

**Posts** (one in each language);

<img width="794" alt="Screenshot 2021-03-09 at 17 03 31" src="https://user-images.githubusercontent.com/841956/110500325-61be3700-80f9-11eb-91cd-205163fcecbb.png">

**Output**

Output of `date_i18n( 'j F Y')` and `get_the_date( 'j F Y')`  for each post:

* **French**: `9 mars 2021`
* **English**: `9 March 2021`
* **German**: `9 März 2021`

So everything in order there.

@markhowellsmead could you try to see if it works for your with the free version?

**Comment by swissspidy** [comment] 2021-03-17 10:33
Closing for now as this is an unconfirmed issue.

**Closed by swissspidy** 2021-03-17 10:33 UTC
Labels: Unconfirmed

**Comment by markhowellsmead** [comment] 2021-03-17 10:44
I cannot replicate this problem in a clean install with the free version of Polylang.
