### ISSUE TITLE
Support: Translation merging

### ISSUE THREAD

**Issue by grappler** [swissspidy/preferred-languages#372] opened 2021-07-06 07:14 UTC
I am trying to get  translation merging to work for `de_CH` with the fallback to `de_DE_formal`.

I have added `add_filter( 'preferred_languages_merge_translations', '__return_true' );` to the child-theme `functions.php`.

I realised it is not working with the example of The Event Calendar. The translation for "All day" exists in [de_DE_formal](https://translate.wordpress.org/projects/wp-plugins/the-events-calendar/stable/de/formal/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=10967490&filters%5Btranslation_id%5D=79318593) but not for [de_CH](https://translate.wordpress.org/projects/wp-plugins/the-events-calendar/stable/de-ch/default/?filters%5Boriginal_id%5D=10967490).

I am not sure why it is not working. @vdwijngaert Do you have an idea?

Could it be because the string does not exist in the `languages/plugins/the-events-calendar-de_CH.po\mo` file but only exists in the `languages/plugins/the-events-calendar-de_DE_formal.po\mo` file?

```
#: src/functions/template-tags/general.php:1276
#: src/views/v2/widgets/widget-events-list/event/date.php:26
msgctxt "All day label for event"
msgid "All day"
msgstr "Ganztägig"
```

**Comment by swissspidy** [comment] 2021-07-06 09:38
Hey Ulrich 🙂 

Thanks for raising this!

I was able to reproduce this issue and spent some time now to improve the way translation merging works. While at it, I also added support for merging JS translations.

Could you give the latest version on `main` a try to see if it now works for you?

**Comment by grappler** [comment] 2021-07-06 10:03
Hey Pascal 👋🏻  It works! 🎉

**Comment by grappler** [comment] 2021-07-06 10:18
Now that is working it creates an interesting scenario that `en_US` does not work `en_US` as the profile language and I have to switch to `en_US`. Not sure if this use case should be supported. 
![image](https://user-images.githubusercontent.com/1785641/124582966-d65c7480-de52-11eb-9461-32658d79c980.png)

I fixed it by changing the code to 
```
add_filter(
	'preferred_languages_merge_translations',
	function ( $merge, $domain, $current_locale ) {
		switch ( $current_locale ) {
			case 'de_CH':
			case 'de_CH_informal':
			case 'de_DE':
			case 'de_DE_formal':
				return true;
			default:
				return $merge;
		}
	},
	10,
	3
);
```

**Comment by vdwijngaert** [comment] 2021-07-06 10:20
> I was able to reproduce this issue and spent some time now to improve the way translation merging works. While at it, I also added support for merging JS translations.

What went wrong?

**Comment by swissspidy** [comment] 2021-07-06 11:22
> Now that is working it creates an interesting scenario that `en_US` does not work `en_US` as the profile language and I have to switch to `en_US`. Not sure if this use case should be supported.
> ![image](https://user-images.githubusercontent.com/1785641/124582966-d65c7480-de52-11eb-9461-32658d79c980.png)
> 
> I fixed it by changing the code to
> 
> ```
> add_filter(
> 	'preferred_languages_merge_translations',
> 	function ( $merge, $domain, $current_locale ) {
> 		switch ( $current_locale ) {
> 			case 'de_CH':
> 			case 'de_CH_informal':
> 			case 'de_DE':
> 			case 'de_DE_formal':
> 				return true;
> 			default:
> 				return $merge;
> 		}
> 	},
> 	10,
> 	3
> );
> ```

Argh, yeah that looks like a regression.

On v1.7.0, choosing `en_US, de_DE` as the user language keeps the whole admin in English.

> > I was able to reproduce this issue and spent some time now to improve the way translation merging works. While at it, I also added support for merging JS translations.
> 
> What went wrong?

The merging in `preferred_languages_load_textdomain_mofile()` was working fine, translations were correctly combined. However, the function returned the first MO file it found, which `load_textdomain()` would then load (again) and merge with what the plugin already loaded, basically undoing the whole merge again.

Code in question:

https://github.com/swissspidy/preferred-languages/blob/e7594208ec492c03d3b5f73f1fea5039fa4d04f1/inc/functions.php#L417-L441

I'm now using the `override_load_textdomain` filter for merging translations, keeping `load_textdomain_mofile` for the non-merging use case (aka return first available MO file found)

**Comment by swissspidy** [comment] 2021-07-06 11:54
> Now that is working it creates an interesting scenario that `en_US` does not work `en_US` as the profile language and I have to switch to `en_US`. Not sure if this use case should be supported.
> ![image](https://user-images.githubusercontent.com/1785641/124582966-d65c7480-de52-11eb-9461-32658d79c980.png)
> 

Just re-reading this again.

It's actually an interesting case. Technically it's correct:

`en_US` does not have any actual translation entries, so `de_CH` jumps in to fill the blanks.

Things would be different if you'd actually create an MO file for `en_US` so that there are translation entries. In that case, there'd be fewer blanks for `de_CH` to fill.

**Comment by grappler** [comment] 2021-07-06 12:19
> Technically it's correct

Yea. It is also a bit of edge case. You could see how many people come across this issue. I don't think many people are using the merge translations feature at the moment.

**Comment by swissspidy** [comment] 2021-07-06 12:29
Yeah makes sense.

Closing this one for now, aiming to release 1.7.1 shortly.

**Closed by swissspidy** 2021-07-06 12:29 UTC
Labels: [Type] Bug
