### ISSUE TITLE
WP5.7 - PL1.7.0 - Profile Language setting not over-riding site default

### ISSUE THREAD

**Issue by raydleemsc** [swissspidy/preferred-languages#366] opened 2021-04-11 13:10 UTC
WP5.7 - PL1.7.0 - Profile Language setting not over-riding site default - is this a thing?

**Comment by raydleemsc** [comment] 2021-04-11 13:11
I put thai as the site default with enguk second, and in my admin profile, put enguk as the default then thai second, and the site is rendering in my admin id as thai. switching the site default back to enguk re-renders the site in enguk

**Comment by swissspidy** [comment] 2021-04-16 07:41
I am unable to verify this at the moment. Does this still happen with all other plugins deactivated and all translations updated? Is it limited to these two locales or does it happen with others as well?

**Comment by AndBaetz** [comment] 2021-04-26 22:21
Have the same or at least a similar problem here with de_DE_formal as first and de_DE as second.

The7 is only translated for de_DE (not formal) and is using the fallback language english then at their WooCommerce templates. Same goes for another plugin.

**Comment by swissspidy** [comment] 2021-05-07 14:09
OK I think I am able to reproduce now.

Site language:

![Screenshot 2021-05-07 at 15 57 55](https://user-images.githubusercontent.com/841956/117460613-ff44b400-af4c-11eb-8f1d-fbfa15bf0782.png)

Profile setting:

![Screenshot 2021-05-07 at 15 58 58](https://user-images.githubusercontent.com/841956/117460764-24d1bd80-af4d-11eb-9760-ab88977bdb59.png)

Frontend is in Thai and the admin is in English as expected. However, when I clear the profile setting (so the site default is used), the admin stays in English (UK), not Thai as expected.

**Comment by ocean90** [comment] 2021-06-03 08:38
@swissspidy I just noticed the same and https://github.com/swissspidy/preferred-languages/commit/cf760407d551eb5aca3c95cd3b07c391ac66680d is working for me.

The current workaround is to deactivate the plugin, reset the language setting in your profile and then activate the plugin again.

**Comment by ocean90** [comment] 2021-06-03 09:01
On second thought, shouldn't the plugin migrate the existing meta to the new setting? Let's say my site language is set to French, but the user language to German. Now I activate the plugin and will see this

<img width="774" alt="Bildschirmfoto 2021-06-03 um 10 59 23" src="https://user-images.githubusercontent.com/617637/120618038-f61b0a00-c45a-11eb-9d2a-9333adcd8d68.png">

Notice that the UI is in German but the setting says I'm using the site default which isn't correct.

**Comment by swissspidy** [comment] 2021-06-03 09:14
Ah, that's a good point! That's definitely odd.

Perhaps `preferred_languages_get_user_list()` could fall back to `get_user_meta( $user->ID, 'user_meta', true )` in that case.

It would just need to temporarily `remove_filter( 'get_user_metadata', 'preferred_languages_filter_user_locale' );` to avoid an infinit loop because it will otherwise call `preferred_languages_get_user_list()` again.

I'll give it a try.

**Comment by swissspidy** [comment] 2021-06-03 16:42
@ocean90 3bae442a34fe90164d92c13b48a3f6d8852e8497 should solve this. Mind testing?

**Comment by ocean90** [comment] 2021-06-05 08:39
@swissspidy It does, but introduces a new issue: You can't remove the language anymore because the `locale` meta doesn't get updated. Should `preferred_languages_update_user_meta()` also set the `locale` meta to empty if `preferred_languages` is empty?

**Comment by swissspidy** [comment] 2021-06-05 10:26
Hmm sounds like it. I‘ll take another look at this then.

**Comment by swissspidy** [comment] 2021-06-07 12:53
Fixed this & a couple of other bugs in `main` now.

**Comment by swissspidy** [comment] 2021-06-28 14:10
@ocean90 any chance you could give the latest changes on `main` a try and see if it solves the issue?

**Comment by grappler** [comment] 2021-07-06 10:23
As I had already installed `main`  for another issue. I thought I could help try and test for this issue too. I tested it using the following steps:

1. Changed profile language
2. Profile language changes
2. Removed all profile languages
3. Profile language reverts to site language

I hope I tested it correctly.

**Comment by swissspidy** [comment] 2021-07-06 11:17
Thanks!

Closing this one for now.

**Closed by swissspidy** 2021-07-06 11:17 UTC
